use chinook;

-- Q1, What is the total revenue generated by the music store?

SELECT ROUND(SUM(total), 2) AS Total_Revenue
FROM invoice;


-- Q2, What is the average amount customers spend per order?

SELECT ROUND(AVG(total), 2) AS Average_Order_Value
FROM invoice;


-- Q3, How many customers have purchased from the store?
SELECT COUNT(*) AS Total_Customers
FROM customer;

-- Q4, Top 10 Customers by Revenue

SELECT c.CustomerId,
    CONCAT(c.FirstName, ' ', c.LastName) AS Customer_Name,
    ROUND(SUM(i.Total), 2) AS Total_Spent
FROM customer c
JOIN invoice i
ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId, Customer_Name
ORDER BY Total_Spent DESC
LIMIT 10;

-- Q5, Which countries generate the highest revenue?

SELECT
    BillingCountry,
    ROUND(SUM(Total),2) AS Revenue
FROM invoice
GROUP BY BillingCountry
ORDER BY Revenue DESC;

-- Q6, Which countries have the largest customer base?
SELECT
    Country,
    COUNT(*) AS Customers
FROM customer
GROUP BY Country
ORDER BY Customers DESC;

-- Q7, Which artists generate the highest revenue?

Select ar.Name AS Artist,
    ROUND(SUM(il.UnitPrice * il.Quantity),2) AS Revenue
FROM invoiceline il
JOIN track t
ON il.TrackId = t.TrackId
JOIN album al
ON t.AlbumId = al.AlbumId
JOIN artist ar
ON al.ArtistId = ar.ArtistId
GROUP BY ar.ArtistId, ar.Name
ORDER BY Revenue DESC
LIMIT 10;

-- Q8, Which music genres are purchased the most?

SELECT
    g.Name AS Genre,
    SUM(il.Quantity) AS Tracks_Sold
FROM invoiceline il
JOIN track t
ON il.TrackId = t.TrackId
JOIN genre g
ON t.GenreId = g.GenreId
GROUP BY g.GenreId, g.Name
ORDER BY Tracks_Sold DESC;


-- Q9, Which tracks are purchased most frequently?
SELECT
    t.Name AS Track,
    SUM(il.Quantity) AS Total_Sold
FROM invoiceline il
JOIN track t
ON il.TrackId = t.TrackId
GROUP BY t.TrackId, t.Name
ORDER BY Total_Sold DESC
LIMIT 10;

-- Q10 How has revenue changed over time?
SELECT
    DATE_FORMAT(InvoiceDate,'%Y-%m') AS Month,
    ROUND(SUM(Total),2) AS Revenue
FROM invoice
GROUP BY Month
ORDER BY Month;

-- Q11, Which support representative generates the highest sales?
SELECT
    CONCAT(e.FirstName,' ',e.LastName) AS Employee,
    ROUND(SUM(i.Total),2) AS Revenue
FROM employee e
JOIN customer c
ON e.EmployeeId = c.SupportRepId
JOIN invoice i
ON c.CustomerId = i.CustomerId
GROUP BY e.EmployeeId, Employee
ORDER BY Revenue DESC;